<?xml version="1.0" encoding="UTF-8"?>
<definitions name="PriceService"
  targetNamespace="http://www.priceserviceservice.com/PriceService"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:tns="http://www.priceserviceservice.com/PriceService"
    xmlns:xsd="http://www.w3.org/1999/XMLSchema">

<import
    location="http://localhost:8080/wsdl/PriceService_Service-interface.wsdl"
    namespace="http://www.priceserviceservice.com/PriceService-interface">
</import>

<service
      name="PriceService">
  <documentation>IBM WSTK 2.0 generated service definition file</documentation>
  <port
      binding="PriceServiceBinding"
        name="PriceServicePort">
    <soap:address location="http://localhost:8080/soap/servlet/rpcrouter"/>
  </port>
</service>

</definitions>
