<?xml version="1.0" encoding="UTF-8"?>
<definitions name="PriceService"
  targetNamespace="http://www.priceserviceservice.com/PriceService-interface"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:tns="http://www.priceserviceservice.com/PriceService"
    xmlns:xsd="http://www.w3.org/1999/XMLSchema">

<message
      name="IngetPriceRequest">
  <part name="meth1_inType1"
    type="xsd:string"/>
</message>

<message
      name="OutgetPriceResponse">
  <part name="meth1_outType"
    type="xsd:double"/>
</message>


<portType
      name="PriceService">
  <operation name="getPrice">
    <input
        message="IngetPriceRequest"/>
    <output
    message="OutgetPriceResponse"/>
  </operation>
</portType>



<binding
    name="PriceServiceBinding" type="PriceService">
  <soap:binding
      style="rpc"
      transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation
        name="getPrice">
    <soap:operation
          soapAction="urn:examples:priceservice"/>
    <input>
      <soap:body
          encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
          namespace="urn:examples:priceservice"
          use="encoded"/>
    </input>
    <output>
      <soap:body
          encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
          namespace="urn:examples:priceservice" use="encoded"/>
    </output>
  </operation>
</binding>

</definitions>
