// generated by GLUE

package com.ecerami.wsdl.glue;

import electric.registry.Registry;
import electric.registry.RegistryException;

public class AirportWeatherHelper
  {
  public static IAirportWeather bind() throws RegistryException
    {
    return bind( "http://www.capescience.com/AirportWeather.wsdl" );
    }

  public static IAirportWeather bind( String url ) throws RegistryException
    {
    return (IAirportWeather) Registry.bind( url, IAirportWeather.class );
    }
  }
