// generated by GLUE

package com.ecerami.wsdl.glue;

import electric.registry.Registry;
import electric.registry.RegistryException;

public class PriceList_ServiceHelper
  {
  public static IPriceList_Service bind() throws RegistryException
    {
    return bind( "http://localhost:8080/wsdl/PriceListService.wsdl" );
    }

  public static IPriceList_Service bind( String url ) throws RegistryException
    {
    return (IPriceList_Service) Registry.bind( url, IPriceList_Service.class );
    }
  }
