// generated by GLUE

package com.ecerami.wsdl.glue;

import electric.registry.Registry;
import electric.registry.RegistryException;

public class Product_ServiceHelper
  {
  public static IProduct_Service bind() throws RegistryException
    {
    return bind( "http://localhost:8080/wsdl/ProductService.wsdl" );
    }

  public static IProduct_Service bind( String url ) throws RegistryException
    {
    return (IProduct_Service) Registry.bind( url, IProduct_Service.class );
    }
  }
