// generated by GLUE

package com.ecerami.wsdl.glue;

public class product
  {
  public java.lang.String name;

  public java.lang.String description;

  public double price;

  public java.lang.String SKU;
  }
