// generated by GLUE

package com.ecerami.wsdl.glue;

public class WeatherSummary
  {
  public java.lang.String location;

  public java.lang.String wind;

  public java.lang.String sky;

  public java.lang.String temp;

  public java.lang.String humidity;

  public java.lang.String pressure;

  public java.lang.String visibility;
  }
